/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppTrackingIdRouteImport } from './routes/app.tracking.$id'
import { Route as AppPickupIdRouteImport } from './routes/app.pickup.$id'
import { Route as AppMenuIdRouteImport } from './routes/app.menu.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingIdRoute = AppTrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPickupIdRoute = AppPickupIdRouteImport.update({
  id: '/pickup/$id',
  path: '/pickup/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuIdRoute = AppMenuIdRouteImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/menu/$id': typeof AppMenuIdRoute
  '/app/pickup/$id': typeof AppPickupIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/menu/$id': typeof AppMenuIdRoute
  '/app/pickup/$id': typeof AppPickupIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/menu/$id': typeof AppMenuIdRoute
  '/app/pickup/$id': typeof AppPickupIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/cart'
    | '/app/checkout'
    | '/app/history'
    | '/app/profile'
    | '/app/'
    | '/app/menu/$id'
    | '/app/pickup/$id'
    | '/app/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/cart'
    | '/app/checkout'
    | '/app/history'
    | '/app/profile'
    | '/app'
    | '/app/menu/$id'
    | '/app/pickup/$id'
    | '/app/tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/cart'
    | '/app/checkout'
    | '/app/history'
    | '/app/profile'
    | '/app/'
    | '/app/menu/$id'
    | '/app/pickup/$id'
    | '/app/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking/$id': {
      id: '/app/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/app/tracking/$id'
      preLoaderRoute: typeof AppTrackingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pickup/$id': {
      id: '/app/pickup/$id'
      path: '/pickup/$id'
      fullPath: '/app/pickup/$id'
      preLoaderRoute: typeof AppPickupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu/$id': {
      id: '/app/menu/$id'
      path: '/menu/$id'
      fullPath: '/app/menu/$id'
      preLoaderRoute: typeof AppMenuIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMenuIdRoute: typeof AppMenuIdRoute
  AppPickupIdRoute: typeof AppPickupIdRoute
  AppTrackingIdRoute: typeof AppTrackingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppMenuIdRoute: AppMenuIdRoute,
  AppPickupIdRoute: AppPickupIdRoute,
  AppTrackingIdRoute: AppTrackingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
